# -*- coding: utf-8 -*-
"""TESTE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hanKBSBEwnb1AtR9ldiUDLOHICSfzU3p
"""

print('{:=^40}'. format(' LOJAS DE VAREJOS '))
preco = float(input('Preso das compras: R$'))
print("""FORMAS DE PAGAMENTO:
    [1] à vista dibheiro/cheque.
    [2] à vista cartão.
    [3] 2x cartão.
    [4] 3x ou mais no catão.""")
opcao = int(input('QUAL É A OPÇÃO? '))
if opcao == 1:
    total = preco - (preco * 10 / 100)
elif opcao == 2:
    total = preco - (preco * 5 / 100)
elif opcao == 3:
    total = preco
    parcela = total / 2
    print(f'A compra será parcela 2x sem jurus de R${parcela:.2f}.')
elif opcao == 4:
    total = preco + (preco * 20 / 100)
    n_parcela = int(input('Quantas parcela? '))
    parcela = total / n_parcela
    print(f'A compra será parcela em {n_parcela}x de R${parcela:.2f} com jurus.')
else:
    total = preco
    print('OPÇÃO INVALIDA! de pagamento. Tente novamente.')
print(f'A compra de R${preco:.2f} custará R${total:.2f} no final.')